# Generated by Django 4.2 on 2024-07-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
