# Generated by Django 4.2 on 2024-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_post_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='illustration',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
    ]
